# NAMESPACE
apiVersion: v1
kind: Namespace
metadata:
  name: app2-ns
  labels:
    type: app2-namespace
    
---
# CONFIGMAP
apiVersion: v1
kind: ConfigMap
metadata:
  name: app2-config
  labels:
    type: app2-configmap
  namespace: app2-ns
data:
  APP1_HOST : http://app1-clusterip-service.app1-ns.svc.cluster.local:8000 #format- <service_name>.<namespace>.svc.cluster.local:port if not 80

---

#SECRETS
apiVersion: v1
kind: Secret
metadata:
  name: app2-secret
  labels:
    type: app2-secret
  namespace: app2-ns
data:
  APP2_SECRET_KEY: MSYyXjMlNCU1
---
#DEPLOYMENT
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app2-deployment
  labels:
    tier: backend
  namespace: app2-ns

spec:

  template:
    metadata:
      name: fastapi-app2-backend-pod
      labels:
        app: fastapi-app2-backend
        tier: backend
      namespace: app2-ns
    
    spec:
      containers:
        - image: deydipankar825/fastapi_app2:version-1.0.2
          name: app2
          envFrom:
            - secretRef:
                name: app2-secret
            - configMapRef:
                name: app2-config

  selector:
    matchLabels:
      app: fastapi-app2-backend
  
  replicas: 2

---
#NODE PORT SERVICE
apiVersion: v1
kind: Service
metadata:
  name: app2-node-port-service
  labels:
    tier: node-port-service
  namespace: app2-ns

spec:
  type: NodePort
  ports:
    - port: 8001
      targetPort: 8001
      nodePort: 30001

  selector:
    app: fastapi-app2-backend

---
#CLUSTER IP SERVICE
apiVersion: v1
kind: Service
metadata:
  name: app2-clusterip-service
  labels:
    tier: clusterip-service
  namespace: app2-ns

spec:
  type: ClusterIP
  ports:
    - port: 8001
      targetPort: 8001
  selector:
    app: fastapi-app2-backend